
import com.sun.glass.events.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Validations extends javax.swing.JFrame {

    /**
     * Creates new form Validations
     */
    public Validations() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name_txtField = new javax.swing.JTextField();
        validaEmail_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        contactNum_txtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        email_txtField = new javax.swing.JTextField();
        valiContact_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        city_txtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        age_txtField = new javax.swing.JTextField();
        valiAge_btn = new javax.swing.JButton();
        valiNicOld_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nicOld_txtfield = new javax.swing.JTextField();
        valiNewNic_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        nicNew_txtField = new javax.swing.JTextField();
        max_btn = new javax.swing.JButton();
        close_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Name");

        name_txtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                name_txtFieldKeyReleased(evt);
            }
        });

        validaEmail_btn.setBackground(new java.awt.Color(153, 153, 153));
        validaEmail_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        validaEmail_btn.setText("Validate E-Mail");
        validaEmail_btn.setMaximumSize(new java.awt.Dimension(149, 25));
        validaEmail_btn.setMinimumSize(new java.awt.Dimension(149, 25));
        validaEmail_btn.setPreferredSize(new java.awt.Dimension(149, 25));
        validaEmail_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validaEmail_btnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Contact No.");

        contactNum_txtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contactNum_txtFieldKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("E-Mail");

        email_txtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                email_txtFieldKeyReleased(evt);
            }
        });

        valiContact_btn.setBackground(new java.awt.Color(153, 153, 153));
        valiContact_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        valiContact_btn.setText("Validate Contact No.");
        valiContact_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valiContact_btnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Age");

        city_txtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                city_txtFieldKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("City");

        age_txtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                age_txtFieldKeyReleased(evt);
            }
        });

        valiAge_btn.setBackground(new java.awt.Color(153, 153, 153));
        valiAge_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        valiAge_btn.setText("Validate Age");
        valiAge_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valiAge_btnActionPerformed(evt);
            }
        });

        valiNicOld_btn.setBackground(new java.awt.Color(153, 153, 153));
        valiNicOld_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        valiNicOld_btn.setText("Validate NIC OLD");
        valiNicOld_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valiNicOld_btnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("NIC OLD");

        nicOld_txtfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicOld_txtfieldKeyReleased(evt);
            }
        });

        valiNewNic_btn.setBackground(new java.awt.Color(153, 153, 153));
        valiNewNic_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        valiNewNic_btn.setText("Validate NIC NEW");
        valiNewNic_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valiNewNic_btnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("NIC NEW");

        nicNew_txtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicNew_txtFieldKeyReleased(evt);
            }
        });

        max_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maximize40_40pix.png"))); // NOI18N
        max_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                max_btnActionPerformed(evt);
            }
        });

        close_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close40_40pix.png"))); // NOI18N
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(28, 28, 28)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(city_txtField, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                                                        .addComponent(age_txtField)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(contactNum_txtField)
                                                                        .addComponent(name_txtField)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(48, 48, 48)
                                                                .addComponent(email_txtField))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(126, 126, 126)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(nicOld_txtfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGap(1, 1, 1)
                                                                .addComponent(nicNew_txtField, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)))))
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(valiNicOld_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                                                .addGap(44, 44, 44))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(close_btn)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(max_btn))
                                                        .addComponent(valiNewNic_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
                                                .addGap(43, 43, 43))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(valiContact_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(validaEmail_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                                                .addGap(50, 50, 50))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(valiAge_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                                .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(name_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(contactNum_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valiContact_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(email_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(validaEmail_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(city_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(age_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(valiAge_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nicOld_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(valiNicOld_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nicNew_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(valiNewNic_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(max_btn)
                                        .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void name_txtFieldKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        char letter = evt.getKeyChar();
        if(Character.isLetter(letter) | evt.getKeyCode() == KeyEvent.VK_SPACE | evt.getKeyCode() == KeyEvent.VK_PERIOD
                | evt.getKeyCode() == KeyEvent.VK_BACKSPACE | evt.getKeyCode() == KeyEvent.VK_CAPS_LOCK | evt.getKeyCode() == KeyEvent.VK_SHIFT | evt.getKeyCode() == KeyEvent.VK_DELETE) {
            name_txtField.setEditable(true);
        }else{
            name_txtField.setEditable(false);
            JOptionPane.showMessageDialog(this,"Use only letters,space,dot,backspace,shift or caps lock.","ERROR!",JOptionPane.ERROR_MESSAGE);
            name_txtField.setText(null);
            name_txtField.grabFocus();
        }
    }

    private void contactNum_txtFieldKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        char digit = evt.getKeyChar();
        if(Character.isDigit(digit)| evt.getKeyCode() == KeyEvent.VK_BACKSPACE | evt.getKeyCode() == KeyEvent.VK_SHIFT | evt.getKeyCode() == KeyEvent.VK_EQUALS | evt.getKeyCode() == KeyEvent.VK_MINUS | evt.getKeyCode() == KeyEvent.VK_DELETE | evt.getKeyCode() == KeyEvent.VK_NUM_LOCK ) {
            contactNum_txtField.setEditable(true);
        }else{
            contactNum_txtField.setEditable(false);
            JOptionPane.showMessageDialog(this,"Use only numbers,backspace,shift,Plus or Minus keys","ERROR!",JOptionPane.ERROR_MESSAGE);
            contactNum_txtField.setText(null);
            contactNum_txtField.grabFocus();
        }

    }

    private void valiContact_btnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String num = contactNum_txtField.getText();
        int charval = num.length();
        if(charval > 8 && charval < 15){
            JOptionPane.showMessageDialog(this,"Valid Number","DONE!",JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this,"Invalid Number","ERROR!",JOptionPane.ERROR_MESSAGE);
            contactNum_txtField.setText(null);
            contactNum_txtField.grabFocus();
        }
    }

    private void email_txtFieldKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        char any = evt.getKeyChar();
        if(Character.isDigit(any)|Character.isLetter(any)|Character.isLowerCase(any)| evt.getKeyCode() == KeyEvent.VK_BACKSPACE | evt.getKeyCode() == KeyEvent.VK_SHIFT | evt.getKeyCode() == KeyEvent.VK_2 | evt.getKeyCode() == KeyEvent.VK_MINUS | evt.getKeyCode() == KeyEvent.VK_DELETE | evt.getKeyCode() == KeyEvent.VK_NUM_LOCK | evt.getKeyCode() == KeyEvent.VK_PERIOD ) {
            email_txtField.setEditable(true);
        }else{
            email_txtField.setEditable(false);
            JOptionPane.showMessageDialog(this,"Use only letters,numbers,backspace,shift,@,dot or Minus keys","ERROR!",JOptionPane.ERROR_MESSAGE);
            email_txtField.setText(null);
            email_txtField.grabFocus();
        }
    }

    private void validaEmail_btnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(email_txtField.getText().contains("@") && email_txtField.getText().contains(".")){
            JOptionPane.showMessageDialog(this,"Valid E-mail","DONE!",JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this,"Invalid E-mail","ERROR!",JOptionPane.ERROR_MESSAGE);
            email_txtField.setText(null);
            email_txtField.grabFocus();
        }
    }

    private void city_txtFieldKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        char letter = evt.getKeyChar();
        if(Character.isLetter(letter) | evt.getKeyCode() == KeyEvent.VK_BACKSPACE | evt.getKeyCode() == KeyEvent.VK_CAPS_LOCK | evt.getKeyCode() == KeyEvent.VK_SHIFT | evt.getKeyCode() == KeyEvent.VK_DELETE) {
            city_txtField.setEditable(true);
        }else{
            city_txtField.setEditable(false);
            JOptionPane.showMessageDialog(this,"Use only letters,backspace,shift","ERROR!",JOptionPane.ERROR_MESSAGE);
            city_txtField.setText(null);
            city_txtField.grabFocus();
        }
    }

    private void age_txtFieldKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        char digit = evt.getKeyChar();
        if(Character.isDigit(digit)| evt.getKeyCode() == KeyEvent.VK_BACKSPACE | evt.getKeyCode() == KeyEvent.VK_SHIFT | evt.getKeyCode() == KeyEvent.VK_DELETE ) {
            age_txtField.setEditable(true);
        }else{
            age_txtField.setEditable(false);
            JOptionPane.showMessageDialog(this,"Use only numbers,backspace,delete","ERROR!",JOptionPane.ERROR_MESSAGE);
            age_txtField.setText(null);
            age_txtField.grabFocus();
        }
    }

    private void valiAge_btnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String num = age_txtField.getText();
        int charval = num.length();
        if(charval > 0 && charval < 4){
            JOptionPane.showMessageDialog(this,"Valid Age","DONE!",JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this,"Invalid Age","ERROR!",JOptionPane.ERROR_MESSAGE);
            age_txtField.setText(null);
            age_txtField.grabFocus();
        }
    }

    private void nicOld_txtfieldKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        char digit = evt.getKeyChar();
        if(Character.isDigit(digit)| evt.getKeyCode() == KeyEvent.VK_BACKSPACE | evt.getKeyCode() == KeyEvent.VK_V | evt.getKeyCode() == KeyEvent.VK_NUM_LOCK | evt.getKeyCode() == KeyEvent.VK_DELETE ) {
            nicOld_txtfield.setEditable(true);
            nicOld_txtfield.setEditable(false);

        }else{
            JOptionPane.showMessageDialog(this,"Use only numbers,backspace,v","ERROR!",JOptionPane.ERROR_MESSAGE);
            nicOld_txtfield.setText(null);
            nicOld_txtfield.grabFocus();
        }
    }

    private void valiNicOld_btnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(nicOld_txtfield.getText().trim().matches("[0-9](9)[v]$")){
            JOptionPane.showMessageDialog(this,"Valid OLD NIC","DONE!",JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this,"Invalid OLD NIC","ERROR!",JOptionPane.ERROR_MESSAGE);
            nicOld_txtfield.setText(null);
            nicOld_txtfield.grabFocus();
        }
    }

    private void nicNew_txtFieldKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        char digit = evt.getKeyChar();
        if(Character.isDigit(digit)| evt.getKeyCode() == KeyEvent.VK_BACKSPACE  | evt.getKeyCode() == KeyEvent.VK_NUM_LOCK | evt.getKeyCode() == KeyEvent.VK_DELETE ) {
            nicNew_txtField.setEditable(true);
            nicNew_txtField.setEditable(false);

        }else{
            JOptionPane.showMessageDialog(this,"Use only numbers,backspace","ERROR!",JOptionPane.ERROR_MESSAGE);
            nicNew_txtField.setText(null);
            nicNew_txtField.grabFocus();
        }
    }

    private void valiNewNic_btnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(nicNew_txtField.getText().trim().matches("[0-9](12)")){
            JOptionPane.showMessageDialog(this,"Valid NEW NIC","DONE!",JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this,"Invalid NEW NIC","ERROR!",JOptionPane.ERROR_MESSAGE);
            nicNew_txtField.setText(null);
            nicNew_txtField.grabFocus();
        }
    }

    private void max_btnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Validations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Validations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Validations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Validations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Validations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField age_txtField;
    private javax.swing.JTextField city_txtField;
    private javax.swing.JButton close_btn;
    private javax.swing.JTextField contactNum_txtField;
    private javax.swing.JTextField email_txtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton max_btn;
    private javax.swing.JTextField name_txtField;
    private javax.swing.JTextField nicNew_txtField;
    private javax.swing.JTextField nicOld_txtfield;
    private javax.swing.JButton valiAge_btn;
    private javax.swing.JButton valiContact_btn;
    private javax.swing.JButton valiNewNic_btn;
    private javax.swing.JButton valiNicOld_btn;
    private javax.swing.JButton validaEmail_btn;
    // End of variables declaration
}
